// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPlZKsUh-D-sNWtI3uASxkLsqedW_Frp4',
    appId: '1:179715410158:web:00d7d65b301413dc920bff',
    messagingSenderId: '179715410158',
    projectId: 'autopick-51616',
    authDomain: 'autopick-51616.firebaseapp.com',
    storageBucket: 'autopick-51616.firebasestorage.app',
    measurementId: 'G-PZP8M3C5TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_VIwxmNY7N8XgkSDcP27FLu4vDFaoMYk',
    appId: '1:179715410158:android:7a5b8f6f7c23e96a920bff',
    messagingSenderId: '179715410158',
    projectId: 'autopick-51616',
    storageBucket: 'autopick-51616.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ3MQTXk8VtQUFuSqbNxr_qVcQ3vPAn20',
    appId: '1:179715410158:ios:e09b98d28c77ee4a920bff',
    messagingSenderId: '179715410158',
    projectId: 'autopick-51616',
    storageBucket: 'autopick-51616.firebasestorage.app',
    iosBundleId: 'com.example.feroser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ3MQTXk8VtQUFuSqbNxr_qVcQ3vPAn20',
    appId: '1:179715410158:ios:e09b98d28c77ee4a920bff',
    messagingSenderId: '179715410158',
    projectId: 'autopick-51616',
    storageBucket: 'autopick-51616.firebasestorage.app',
    iosBundleId: 'com.example.feroser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPlZKsUh-D-sNWtI3uASxkLsqedW_Frp4',
    appId: '1:179715410158:web:b9f8231c9be67f51920bff',
    messagingSenderId: '179715410158',
    projectId: 'autopick-51616',
    authDomain: 'autopick-51616.firebaseapp.com',
    storageBucket: 'autopick-51616.firebasestorage.app',
    measurementId: 'G-9WN9440960',
  );
}
